### ISSUE TITLE
Is it open source ? (license ?)

### ISSUE THREAD

**Issue by titsitits** [jtguan/Wavelet-Deep-Neural-Network-for-Stripe-Noise-Removal#1]
Hi,
I am currently working on a project to develop an open source image restoration pipeline. Your approach for stripe noise removal is interesting and I would like to try it out. However, it would be a loss of time for me if I cannot use it afterwards, so I would like if your project is intended to be open source, and if so, under which license ?
For now, I integrated a gaussian noise removal, a super-resolution and a colorization technique, all with MIT or Apache license, and it would be interesting to see if stripe noise removal improves the pipe.
Thanks

**Comment by jtguan** [comment]
Of Course, You can use and modify the code at will. Please attach a link to the source project and our paper ‘’Guan J, Lai R, Xiong A, et al. Wavelet Deep Neural Network for Stripe Noise Removal[J]. IEEE Access, 2019: 44544.”
If you have any question, please contact me:  jtguan@stu.xidian.edu.cn

**Comment by titsitits** [comment]
Hi, many thanks for your positive answer. I am making some test with promising results. I plan to add your method to my pipeline (and cite it properly of course!).
I just saw that you add an image for the CC-BY licence. Just note that CC license are not recommended for softwares: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

Anyway, to add a license to you repository, you can add a "license.md" file to your repository and github automatically detects the license. See for example my repo (I am using an Apache license): https://github.com/titsitits/open-image-restoration

**Comment by jtguan** [comment]
Thanks for your help. I have added the Apache License in my repo.  I am so sorry that I'm not familiar with the open-source licenses. If there are still problems, please contact me in time.

**Comment by titsitits** [comment]
Hi, thank you for your reponsiveness, it is perfect like this. I will reference your work in my repo asap ;)

**Comment by titsitits** [comment]
Hi, as I said, I included your project in my repo: https://github.com/titsitits/open-image-restoration
(i'll add a demo notebook when I find more time ;) )
